//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.08.12 at 02:55:19 PM IST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.example.org/spring/soap/api/loaneligibility", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package org.example.spring.soap.api.loaneligibility;
